#!/usr/bin/env bash

[[ \
  ! -z "$EKS_CLUSTER_URL" \
  &&  ! -z "$EKS_CLUSTER_NAME" \
  &&  ! -z "$AWS_REGION" \
]] && mkdir -p "$HOME/.kube" && cat <<EOD | tee "$HOME/.kube/config" > /dev/null 2>&1
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: $EKS_CLUSTER_URL
  name: eks
contexts:
- context:
    cluster: eks
    user: eks
  name: eks
current-context: eks
kind: Config
preferences: {}
users:
- name: eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - $AWS_REGION
      - eks
      - get-token
      - --cluster-name
      - $EKS_CLUSTER_NAME
      command: aws
EOD

exec "$@"